version: '3.5'

services:
  folkmq-server-broker:
    image: noearorg/folkmq-server-broker:1.5.2
    container_name: folkmq-server-broker
    ports:
      - 8602:8602
      - 18602:18602 #mq: tcp 端口
#      - 18603:18603 #mq: websocket 端口
    volumes:
      - ./data/broker:/data
      - ./logs/broker:/logs
    environment:
      - folkmq.admin=admin  #管理后台密码（暂时没有管理后台）
#      - folkmq.websocket=true #启用 websocket 端口
#      - folkmq.access.ak=demo              #消息访问账号
#      - folkmq.access.sk=YapLHTx19RlsEE16  #消息访问密钥
      - TZ=Asia/Shanghai
    networks:
      folkmq:
        aliases:
          - folkmq-server-broker
  folkmq-server1:
    image: noearorg/folkmq-server:1.5.2
    container_name: folkmq-server1
    ports:
      - 8611:8602
      - 18611:18602
    volumes:
      - ./logs/server1:/logs
      - ./data/server1:/data
    environment:
      - folkmq.broker=folkmq://folkmq-server-broker:18602
      - solon.start.ping=folkmq-server-broker:8602
      - TZ=Asia/Shanghai
    depends_on:
      - folkmq-server-broker
    networks:
      folkmq:
        aliases:
          - folkmq-server1
  folkmq-server2:
    image: noearorg/folkmq-server:1.5.2
    container_name: folkmq-server2
    ports:
      - 8612:8602
      - 18612:18602
    volumes:
      - ./data/server2:/data
      - ./logs/server2:/logs
    environment:
      - folkmq.broker=folkmq://folkmq-server-broker:18602
      - solon.start.ping=folkmq-server-broker:8602
      - TZ=Asia/Shanghai
    depends_on:
      - folkmq-server-broker
    networks:
      folkmq:
        aliases:
          - folkmq-server2
networks:
  folkmq:
    name: folkmq
    driver: bridge
