version: '3.5'

services:
  folkmq-server:
    image: noearorg/folkmq-server:1.4.3
    container_name: folkmq-server
    environment:
      - folkmq.admin=admin  #管理后台密码
#      - folkmq.access.ak=demo              #消息访问账号
#      - folkmq.access.sk=YapLHTx19RlsEE16  #消息访问密钥
      - TZ=Asia/Shanghai
    ports:
      - 8602:8602           #管理后台端口
      - 18602:18602         #消息服务端口
    volumes:
      - ./logs/server:/logs
      - ./data/server:/data