version: '3.5'

services:
  folkmq-proxy:
    image: noearorg/folkmq-proxy:1.6.0
    container_name: folkmq-proxy
    ports:
      - 8602:8602
      - 18602:18602 #mq: tcp 端口
#      - 18603:18603 #mq: websocket 端口
    volumes:
      - ./data/broker:/data
      - ./logs/broker:/logs
    environment:
      - folkmq.admin=admin  #管理后台密码（暂时没有管理后台）
#      - folkmq.websocket=true #启用 websocket 端口
#      - folkmq.access.ak=demo              #消息访问账号
#      - folkmq.access.sk=YapLHTx19RlsEE16  #消息访问密钥
      - TZ=Asia/Shanghai
    networks:
      folkmq:
        aliases:
          - folkmq-proxy
  folkmq-broker1:
    image: noearorg/folkmq-broker:1.6.0
    container_name: folkmq-broker1
    ports:
      - 8611:8602
      - 18611:18602
    volumes:
      - ./logs/server1:/logs
      - ./data/server1:/data
    environment:
      - folkmq.proxy=folkmq://folkmq-proxy:18602
      - solon.start.ping=folkmq-proxy:8602
      - TZ=Asia/Shanghai
    depends_on:
      - folkmq-proxy
    networks:
      folkmq:
        aliases:
          - folkmq-broker1
  folkmq-broker2:
    image: noearorg/folkmq-broker:1.6.0
    container_name: folkmq-broker2
    ports:
      - 8612:8602
      - 18612:18602
    volumes:
      - ./data/server2:/data
      - ./logs/server2:/logs
    environment:
      - folkmq.proxy=folkmq://folkmq-proxy:18602
      - solon.start.ping=folkmq-proxy:8602
      - TZ=Asia/Shanghai
    depends_on:
      - folkmq-proxy
    networks:
      folkmq:
        aliases:
          - folkmq-broker2
networks:
  folkmq:
    name: folkmq
    driver: bridge
