server.port: 8602

server.session:
  state.jwt.secret: "YTkBY+iXQxPt6e3UG4/VRHAHXePJZTSyc3cAE6btwfI="

solon.app:
  group: folkmq
  name: folkmq-server
  stop:
    delay: "4s"

solon.logging.appender:
  console:
    level: INFO
  file:
    level: INFO
    name: "logs/${solon.app.name}"
    rolling: "logs/${solon.app.name}_%d{yyyy-MM-dd}/%i.log"
    maxFileSize: "10 MB"
    maxHistory: "7"

solon.logging.logger:
  "root": #默认记录器配置
    level: INFO
  "io.netty":
    level: ERROR

folkmq:
  path: ""
  admin: admin
  schema: ""
  maxConsumeWaiting: "180s"

#folkmq.api.token: "GhVPG@hjJMViC7xN"
#folkmq.broker: "folkmq://127.0.0.1:18602"

#folkmq.access:
#  ak : "demo"
#  sk : "YapLHTx19RlsEE16"